name: Docker Push

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  dockerhub:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        build-args: |
          VERSION=${{ github.event.release.tag_name }}
        tags: |
          dmachard/dnscollector:${{ github.event.release.tag_name }}
          dmachard/dnscollector:latest
          dmachard/go-dnscollector:${{ github.event.release.tag_name }}
          dmachard/go-dnscollector:latest
